# Generated by Django 4.2.13 on 2026-05-02 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaygroundSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "environment_type",
                    models.CharField(
                        choices=[
                            ("docker", "Docker"),
                            ("kubernetes", "Kubernetes"),
                            ("linux", "Linux"),
                        ],
                        default="linux",
                        max_length=20,
                    ),
                ),
                (
                    "docker_image",
                    models.CharField(default="ubuntu:22.04", max_length=200),
                ),
                ("container_id", models.CharField(blank=True, max_length=200)),
                (
                    "websocket_token",
                    models.CharField(blank=True, max_length=64, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisioning"),
                            ("active", "Active"),
                            ("stopped", "Stopped"),
                            ("expired", "Expired"),
                        ],
                        default="provisioning",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playground_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "playground_sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
