# Generated by Django 4.2.13 on 2026-05-02 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField(help_text="Supports Markdown")),
                ("short_description", models.CharField(blank=True, max_length=300)),
                ("thumbnail_url", models.URLField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("duration_minutes", models.PositiveSmallIntegerField(default=30)),
                (
                    "environment_type",
                    models.CharField(
                        choices=[
                            ("docker", "Docker"),
                            ("kubernetes", "Kubernetes"),
                            ("git", "Git"),
                            ("linux", "Linux"),
                            ("terraform", "Terraform"),
                        ],
                        default="docker",
                        max_length=20,
                    ),
                ),
                (
                    "docker_image",
                    models.CharField(
                        default="ubuntu:22.04",
                        help_text="Docker image used to provision the lab container",
                        max_length=200,
                    ),
                ),
                (
                    "k8s_manifest_template",
                    models.JSONField(
                        blank=True,
                        help_text="Kubernetes manifest template for K8s labs (JSON)",
                        null=True,
                    ),
                ),
                ("points_reward", models.PositiveIntegerField(default=100)),
                ("is_free", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_completions", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "labs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Lucide icon name", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex color for UI badge",
                        max_length=7,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Lab Categories",
                "db_table": "lab_categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LabSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("provisioning", "Provisioning"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("container_id", models.CharField(blank=True, max_length=200)),
                ("container_host", models.CharField(blank=True, max_length=200)),
                ("container_port", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "websocket_token",
                    models.CharField(blank=True, max_length=64, unique=True),
                ),
                ("current_task_index", models.PositiveSmallIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="labs.lab",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lab_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LabTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Instructions shown to user (Markdown)"),
                ),
                (
                    "hint",
                    models.TextField(
                        blank=True, help_text="Hint shown on request (Markdown)"
                    ),
                ),
                (
                    "validation_type",
                    models.CharField(
                        choices=[
                            ("script", "Bash Script"),
                            ("command_output", "Command Output Match"),
                            ("file_exists", "File Exists"),
                            ("api_check", "HTTP API Check"),
                        ],
                        default="script",
                        max_length=20,
                    ),
                ),
                (
                    "validation_script",
                    models.TextField(
                        blank=True,
                        help_text="Bash script run inside container to validate. Must echo PASS/FAIL and exit 0/1.",
                    ),
                ),
                (
                    "expected_output",
                    models.CharField(
                        blank=True,
                        help_text="String, regex pattern, or JSON for output comparison",
                        max_length=500,
                    ),
                ),
                ("points", models.PositiveSmallIntegerField(default=20)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="labs.lab",
                    ),
                ),
            ],
            options={
                "db_table": "lab_tasks",
                "ordering": ["lab", "order"],
                "unique_together": {("lab", "order")},
            },
        ),
        migrations.AddField(
            model_name="lab",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="labs",
                to="labs.labcategory",
            ),
        ),
        migrations.AddField(
            model_name="lab",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labs_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="LabSessionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_tasks",
                        to="labs.labsession",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_tasks",
                        to="labs.labtask",
                    ),
                ),
            ],
            options={
                "db_table": "lab_session_tasks",
                "ordering": ["task__order"],
                "unique_together": {("session", "task")},
            },
        ),
        migrations.CreateModel(
            name="LabRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="labs.lab",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lab_ratings",
                "ordering": ["-created_at"],
                "unique_together": {("user", "lab")},
            },
        ),
    ]
